//
// Created by ek on 25.03.2022.
//

#ifndef INC_3DCG_RESEARCH_AND_IMPLEMENTATION_GEOMETRYSHAPE_H
#define INC_3DCG_RESEARCH_AND_IMPLEMENTATION_GEOMETRYSHAPE_H


class geometryShape {

};


#endif //INC_3DCG_RESEARCH_AND_IMPLEMENTATION_GEOMETRYSHAPE_H
