//
// Created by ek on 26.03.2022.
//

#ifndef INC_3DCG_RESEARCH_AND_IMPLEMENTATION_UTILS_H
#define INC_3DCG_RESEARCH_AND_IMPLEMENTATION_UTILS_H





#endif //INC_3DCG_RESEARCH_AND_IMPLEMENTATION_UTILS_H
